[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "9HbZeMEAbAQi9BfkqMWTVEyPpgrh4v1jCpyDuuopkRDK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/eskaine/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
